apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-11T15:18:03Z"
  generation: 2
  labels:
    app: highscore
  name: highscore
  namespace: arcade
  resourceVersion: "55816"
  uid: 427cdf5c-7c82-40e2-b83d-bbf776ba55c0
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: highscore
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: highscore
    spec:
      containers:
      - image: quay.io/mdewald/s3e-highscore
        imagePullPolicy: Always
        name: s3e-highscore
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-06-11T15:18:03Z"
    lastUpdateTime: "2022-06-11T15:18:15Z"
    message: ReplicaSet "highscore-5fcc655d4f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-06-13T14:37:02Z"
    lastUpdateTime: "2022-06-13T14:37:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
