apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-11T15:15:53Z"
  generation: 2
  labels:
    app: platform
  name: platform
  namespace: arcade
  resourceVersion: "55722"
  uid: 56c3958d-9ca4-45b0-8d90-eb29aa4ad032
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: platform
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: platform
    spec:
      containers:
      - image: quay.io/mdewald/s3e-platform
        imagePullPolicy: Always
        name: s3e-platform
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-06-11T15:15:53Z"
    lastUpdateTime: "2022-06-11T15:16:00Z"
    message: ReplicaSet "platform-799b8cb6c8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-06-13T14:36:20Z"
    lastUpdateTime: "2022-06-13T14:36:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
