apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-06-13T14:05:01Z"
  labels:
    app: game
  name: game
  namespace: arcade
  resourceVersion: "53765"
  uid: 91502e87-1898-4c99-a830-5c523d51fbb3
spec:
  clusterIP: 10.109.49.175
  clusterIPs:
  - 10.109.49.175
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: game
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
