apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-06-11T15:05:08Z"
  labels:
    kubernetes.io/metadata.name: arcade
  name: arcade
  resourceVersion: "37311"
  uid: 749248b4-adf5-4dc6-828f-819c0812fab1
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
