---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fight-config
  namespace: superheroes
data:
  mongodb_username: root
  mongodb_password: root
  mongodb_database: rest-fight
  mongodb_connection_string: mongodb://fight-database:27017/rest-fight
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 981b214bd759c35065965f17c2edabdfc03969cf
    app.quarkus.io/build-timestamp: 2023-04-05 - 12:41:02 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: rest-fight
  name: rest-fight
  namespace: superheroes
spec:
  ingressClassName: nginx
  rules:
    - host: superheroes.com
      http:
        paths:
          - backend:
              service:
                name: rest-fight
                port:
                  number: 80
            path: /api/fights
            pathType: Prefix
    - host: ""
      http:
        paths:
          - backend:
              service:
                name: rest-fight
                port:
                  name: http
            path: /
            pathType: Prefix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fight-database
  namespace: superheroes
spec:
  selector:
    matchLabels:
      name: fight-database
  template:
    metadata:
      labels:
        name: fight-database
      namespace: superheroes
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: mongodb_username
                  name: fight-config
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: mongodb_password
                  name: fight-config
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: mongodb_database
                  name: fight-config
          image: mongo
          imagePullPolicy: IfNotPresent
          name: fight-database
          ports:
            - containerPort: 27017
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fight-database
  namespace: superheroes
spec:
  ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    name: fight-database
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 981b214bd759c35065965f17c2edabdfc03969cf
    app.quarkus.io/build-timestamp: 2023-04-05 - 12:41:02 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: rest-fight
  name: rest-fight
  namespace: superheroes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: rest-fight
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 981b214bd759c35065965f17c2edabdfc03969cf
        app.quarkus.io/build-timestamp: 2023-04-05 - 12:41:02 +0000
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: rest-fight
      namespace: superheroes
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jeremygilbert/rest-fight:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: rest-fight
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: rest-fight
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 981b214bd759c35065965f17c2edabdfc03969cf
    app.quarkus.io/build-timestamp: 2023-04-05 - 12:41:02 +0000
  labels:
    app.kubernetes.io/name: rest-fight
    app.kubernetes.io/version: 1.0.0
  name: rest-fight
  namespace: superheroes
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: rest-fight
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 981b214bd759c35065965f17c2edabdfc03969cf
    app.quarkus.io/build-timestamp: 2023-04-05 - 12:41:02 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: rest-fight
  name: rest-fight
  namespace: superheroes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rest-fight-view
  namespace: superheroes
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: rest-fight
    namespace: superheroes
