---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: b92bf4d3c368c2bc520f682d611ef057318ebe98
    app.quarkus.io/build-timestamp: 2023-04-05 - 07:40:28 +0000
  labels:
    app.kubernetes.io/name: rest-statistic
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: rest-statistic
  namespace: superheroes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rest-statistic
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: b92bf4d3c368c2bc520f682d611ef057318ebe98
        app.quarkus.io/build-timestamp: 2023-04-05 - 07:40:28 +0000
      labels:
        app.kubernetes.io/name: rest-statistic
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      namespace: superheroes
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jeremygilbert/rest-statistic:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: rest-statistic
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: b92bf4d3c368c2bc520f682d611ef057318ebe98
    app.quarkus.io/build-timestamp: 2023-04-05 - 07:40:28 +0000
  labels:
    app.kubernetes.io/name: rest-statistic
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: rest-statistic
  namespace: superheroes
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  selector:
    app.kubernetes.io/name: rest-statistic
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
